version: '3'

services:
  hfm-user-account-management-service:
    networks:
      - hfm-user-account-management-service
    container_name: hfm_user_account_management_service
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/usr/src/app
    depends_on:
      - db-hfm-user-account-management-service
    links:
      - db-hfm-user-account-management-service:db-hfm-user-account-management-service
  db-hfm-user-account-management-service:
    networks:
      - hfm-user-account-management-service
    container_name: db_hfm_user_account_management_service
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

networks:
  hfm-user-account-management-service:
